inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
  NewCops: enable

Style/Documentation:
  Enabled: false