services:
  db:
    container_name: e-commerce-db
    image: mysql:8.3.0
    volumes:
      - mysql-volume:/var/lib/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
  app:
    container_name: e-commerce-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
  web:
    container_name: e-commerce-proxy
    image: nginx:1.25.4
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
volumes:
  mysql-volume: